do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('shopping/', include('shopping.urls')), #서버IP/shopping
    path('admin/', admin.site.urls), #서버IP/admin
    path('', include('single_pages.urls')), #서버IP/
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #서버IP/media

shopping/urls.py
from django.urls import path
from . import views

urlpatterns = [
#    path('<int:pk>/', views.single_post_page),
#    path('', views.index), #서버IP/shopping

    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>', views.category_page),
    path('manufacture/<str:slug>', views.manufacture_page),
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
]

shopping/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shopping/category/{self.slug}'
    class Meta:
        verbose_name_plural = 'Categories'

class Manufacture(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return f'/shopping/manufacture/{self.slug}'

class Post(models.Model):
    title = models.CharField(max_length=30)
    price = models.CharField(max_length=30)
    volume = models.CharField(max_length=30)

    content = MarkdownxField()
    packing = models.CharField(max_length=30)

    head_image = models.ImageField(upload_to='shopping/images/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    manufacture = models.ForeignKey(Manufacture, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/shopping/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists() :
            return self.author.socialaccount_set.first().get_avatar_url()
        else :
            return 'https://doitdjango.com/avatar/id/448/889e08cc25fd3f94/svg/{self.author.email}/'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists() :
            return self.author.socialaccount_set.first().get_avatar_url()
        else :
            return 'https://doitdjango.com/avatar/id/448/889e08cc25fd3f94/svg/{self.author.email}/'

shopping/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

shopping/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Category, Manufacture, Comment
from django.core.exceptions import PermissionDenied
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST' :
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else :
            return redirect(post.get_absolute_url())
    else :
        raise PermissionDenied

# Create your views here.

class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model =Post
    fields = ['title', 'price', 'volume', 'content', 'packing', 'head_image', 'category', 'manufacture']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser) :
            form.instance.author = current_user
            return super(PostCreate,self).form_valid(form)
        else :
            return redirect('/shopping/')

class PostUpdate(LoginRequiredMixin,UpdateView): # 모델명_form
    model = Post
    fields = ['title', 'price', 'volume', 'content', 'packing', 'head_image', 'category', 'manufacture']

    template_name = 'shopping/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author :
            return super(PostUpdate,self).dispatch(request, *args, **kwargs)
        else :
            raise PermissionDenied

class PostList(ListView) :
    model = Post
    ordering = 'pk'
    paginate_by = 8
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['manufactures'] = Manufacture.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        return context

#    template_name = 'shopping/post_list.html'
#post_list.html

class PostDetail(DetailView) :
    model = Post

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['manufactures'] = Manufacture.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context

#post_detail.html

class PostSearch(PostList) :
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q}({self.get_queryset().count()})'

        return context

def category_page(request, slug):
    if slug == 'no_category' :
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else :
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)
    return render(request, 'shopping/post_list.html',
                  {
                      'post_list' : post_list,
                      'categories' : Category.objects.all(),
                      'no_category_post_count' : Post.objects.filter(category=None).count(),
                      'category' : category
                  }
                  )

def manufacture_page(request, slug):
    if slug == 'no_manufacture' :
        manufacture = '미분류'
        post_list = Post.objects.filter(manufacture=None)
    else :
        manufacture = Manufacture.objects.get(slug=slug)
        post_list = Post.objects.filter(manufacture=manufacture)
    return render(request, 'shopping/post_list.html',
                  {
                      'post_list' : post_list,
                      'manufactures' : Manufacture.objects.all(),
                      'no_manufacture_post_count' : Post.objects.filter(manufacture=None).count(),
                      'manufacture' : manufacture
                  }
                  )

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model=Comment
    form_class=CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post=comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

#def index(request) :
#    posts = Post.objects.all().order_by('pk')
#    return render(request, 'shopping/post_list.html',
#                  {
#                      'posts' : posts
#                  }
#                  )

#def single_post_page(request, pk) :
#    post = Post.objects.get(pk=pk)
#
#    return render(request, 'shopping/post_detail.html',
#                  {
#                      'post': post
#                  }
#                  )

shopping/templates/shopping/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
    <title>{% block head_title %}Shopping{% endblock %}</title>
    <link href = "{% static 'shopping/bootstrap/bootstrap.min.css' %}" rel = "stylesheet" type = "text/css" media="screen">
        <link href = "{% static 'shopping/css/shopping-post.css' %}" rel = "stylesheet" type = "text/css" media="screen">
        <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://kit.fontawesome.com/0eacb1d254.js" crossorigin="anonymous"></script>

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type = "text/css" media="screen" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'shopping/bootstrap/styles.css' %}" rel = "stylesheet" rel = "stylesheet" type = "text/css" media="screen" />
</head>

<body>
{% include 'shopping/navbar.html' %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder" style="padding-top :50px">당신은 스스로에게 만족스러운 향수를 사용하고 있나요?</h1>
                    <p class="lead fw-normal text-white-50 mb-0">나만의 향으로 당신의 하루를 바꿔보세요</p>
                </div>
            </div>
        </header>
        <div class="container my-3">
            <div class="row">
                <div class="col-md-8 col-lg-9" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                    </div>
                <div class="col-md-4 col-lg-3">
                    <!-- Search widget-->
           <div class="card mb-4">
            <div class="card-header"><i class="fas fa-search"></i>&nbsp;&nbsp;Search</div>
            <div class="card-body">
                <div class="input-group">
                    <input class="form-control" type="text" id="search-input" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                    <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost()">Go!</button>
                </div>
            </div>
        </div>
        <!-- Categories widget-->
        <div class="card mb-4" id="categories-card">
            <div class="card-header">Categories</div>
            <div class="card-body">
                <div class="row">
                        <ul class="list-unstyled mb-0">
                            {% for c in categories %}
                            <li><a href="http://127.0.0.1:49236/shopping/category/{{c.slug}}">{{c}} ({{c.post_set.count}})</a></li>
                            {% endfor %}
                            <li><a href="http://127.0.0.1:49236/shopping/category/no_category">미분류 ({{post_set.count}})</a></li>

                        </ul>
                </div>
            </div>
        </div>
                    <div class="card mb-4">
            <div class="card-header">Manufacture</div>
            <div class="card-body">
                <div class="row">
                        <ul class="list-unstyled mb-0">
                            {% for c in manufactures %}
                            <li><a href="http://127.0.0.1:49236/shopping/manufacture/{{c.slug}}">{{c}} ({{c.post_set.count}})</a></li>
                            {% endfor %}
                            <li><a href="http://127.0.0.1:49236/shopping/manufacture/no_manufacture">미분류 ({{post_set.count}})</a></li>

                        </ul>
                </div>
            </div>
        </div>
                </div>
                </div>

            </div>
        </div>
        </div>

<script>
    function searchPost(){
     let searchValue = document.getElementById('search-input').value.trim();
     if(searchValue.length > 1){
     location.href = "/shopping/search/" + searchValue + "/";
    }
    else{
    alert('검색어(' + searchValue+ ')가 너무 짧습니다.');
    }
    };
    document.getElementById('search-input').addEventListener('keyup',
                    function(event) {
                     if(event.key == 'Enter') { searchPost();}
                    }
                    )
</script>


{% include 'shopping/footer.html' %}


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

shopping/templates/shopping/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
    <title>{% block head_title %}Shopping{% endblock %}</title>
    <link href = "{% static 'shopping/bootstrap/bootstrap.min.css' %}" rel = "stylesheet" type = "text/css" media="screen">
        <link href = "{% static 'shopping/css/shopping-post.css' %}" rel = "stylesheet" type = "text/css" media="screen">
        <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <script src="https://kit.fontawesome.com/0eacb1d254.js" crossorigin="anonymous"></script>

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type = "text/css" media="screen" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'shopping/bootstrap/styles.css' %}" rel = "stylesheet" rel = "stylesheet" type = "text/css" media="screen" />
</head>

<body>
{% include 'shopping/navbar.html' %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">당신은 스스로에게 만족스러운 향수를 사용하고 있나요?</h1>
                    <p class="lead fw-normal text-white-50 mb-0">나만의 향으로 당신으 하루를 바꿔보세요</p>
                </div>
            </div>
        </header>
        <div class="container my-3">
            <div class="row">
                <div class="col-md-8 col-lg-9" id="main-area">
                    {% block main_area %}
                    {% endblock %}
                    </div>
                <div class="col-md-4 col-lg-3">


                </div>
                </div>

            </div>
        </div>
        </div>

{% include 'shopping/footer.html' %}


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

    </body>
</html>

shopping/templates/shopping/comment_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Shopping{% endblock %}
{% block main_area %}
<h1>Edit Comment</h1>
<hr />
<form method="post" id="comment-form">
  {% csrf_token %}
    {{form | crispy}}
  <br>
  <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{% endblock %}

shopping/templates/shopping/footer.html
<!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">주소: 서울특별시 도봉구 삼양로 144길 33  고객센터: 02-1234-4567 평일 10:00 ~ 18:00 / 점심시간 13:00 ~ 14:00
(주말, 공휴일 휴무)
오프라인 : 화-토요일 11:00 ~ 20:00 / 점심시간 13:00~14:00 (일, 월요일 휴무)</p></div>
        </footer>

shopping/templates/shopping/post_detail.html
{% extends 'shopping/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ post.title }} - Shopping
{% endblock %}
{% block main_area %}
                    <!-- Section-->
        <section class="py-5" id="post-area">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6">
                        {% if post.head_image %}
                        <img class="card-img-top mb-5 mb-md-0" src="{{ post.head_image.url }}" alt="{{post.title}}의 head image" />
                        {% else %}
                        <img class="card-img-top" src="http://picsum.photos/seed/{{post.id}}/100/100" alt="random image" />
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        <div class="small mb-1">SKU: BST-498</div>
                        <h1 class="display-5 fw-bolder">{{ post.title }}</h1>
                        <div>
                                {% if user.is_authenticated and user == post.author %}
                                <a href="/shopping/update_post/{{post.pk}}/" class="btn btn-info btn-sm float-right">
                                    <i class="fas fa-pen"></i>
                                    Edit Post
                                </a>
                                {% endif %}
                            </div>
                        <div class="fs-5 mb-5">
                            <span>{{ post.price }}&nbsp;&nbsp;<a class="btn btn-outline-dark mt-auto" href="#"><i class="far fa-heart"></i></a></span>
                        </div>
                        <div>
                                    {% if post.category %}
                                    <span class="badge bg-secondary">{{post.category}}</span>
                                    {% else %}
                                    <span class="badge bg-secondary">미분류</span>
                                    {% endif %}
                                    {% if post.manufacture %}
                                    <span class="badge bg-secondary">{{post.manufacture}}</span>
                                    {% else %}
                                    <span class="badge bg-secondary">미분류</span>
                                    {% endif %}
                                    </div>
                        <p class="lead">{{ post.get_content_markdown | safe }}</p>
                        <p class="lead">용량: {{ post.volume }}ml</p>
                        <p class="lead">포장봉투 제공: {{ post.packing }}개</p>
                      <p class="lead">판매 시작: {{ post.created_at | date:"20y-m-d" }}</p>
                        <div class="d-flex">
                            <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                <i class="bi-cart-fill me-1"></i>
                                Add to cart
                            </button>

                        </div>
                    </div>
                </div>
            </div>
        </section>


<!-- Comments section-->
                    <section class="mb-5" id="comment-area">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if user.is_authenticated %}
                                <form class="mb-4" id="comment-form" method="POST" action="{{post.get_absolute_url}}new_comment/">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{comment_form | crispy}}
                                    </div>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                                {% else %}
                                <a role="button" class="btn btn-outline-dark" href="#"
                                data-toggle="modal" data-target="#loginModal"
                                >Log in and leave a comment</a>
                                {% endif %}
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
<div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                                </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {% if post.comment_set.all.exists %}
                                {% for comment in post.comment_set.all %}
                                <!-- Single comment-->
                                <div class="d-flex" id="comment-{{comment.pk}}">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="{{comment.get_avatar_url}}" alt="{{comment.author}}" width="60px" /></div>
                                    <div class="ms-3">
                                        {% if user.is_authenticated and comment.author == user %}
                                        <div class="float-right">
                                            <a role="button" class="btn btn-sm btn-info" id="comment-{{ comment.pk }}-update-btn" href="/shopping/update_comment/{{ comment.pk }}/">Edit</a>
                                            <a role="button" href="#" class="btn btn-sm btn-danger" id="comment-{{ comment.pk }}-delete-modal-btn" data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">Delete</a>
                                        </div>

                                        <!-- Modal -->
<div class="modal fade" id="deleteCommentModal-{{ comment.pk }}" tabindex="-1" aria-labelledby="deleteCommentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteCommentModalLabel">Are You Sure?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <del>{{ comment | linebreaks }}</del>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <a role="button" class="btn btn-danger" href="/shopping/delete_comment/{{ comment.pk }}/">Delete</a>
        </div>
      </div>
    </div>
  </div>

                                        {% endif %}
                                        <div class="fw-bold">{{comment.author.username}} &nbsp;&nbsp;&nbsp;
                                            <small class="text-muted">({{comment.created_at}})</small></div>
                                        <p>{{comment.content | linebreaks}}</p>
                                    </div>
                                </div>
                                {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </section>

{% endblock %}

shopping/templates/shopping/post_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Create Post - Shopping{% endblock %}
{% block main_area %}
<h1>Create New Post</h1>
<hr />
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{form | crispy}}
  <br>
  <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{{form.media}}
{% endblock %}

shopping/templates/shopping/post_update_form.html
{% extends 'shopping/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Post - Shopping{% endblock %}
{% block main_area %}
<h1>Create New Post</h1>
<hr />
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{form | crispy}}
  <br>
  <button type="submit" class="btn btn-primary float-right">Submit</button>
</form>
{{form.media}}
{% endblock %}